name: Validate PR Description

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-description:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR description
        run: |
          DESCRIPTION="$(jq -r .pull_request.body "$GITHUB_EVENT_PATH")"
          echo "PR Description: $DESCRIPTION"

          # Extract line after "* Please describe your changes:"
          DESC_LINE=$(echo "$DESCRIPTION" | grep -A1 '\* Please describe your changes:' | tail -n1 | xargs)

          echo "Parsed description: '$DESC_LINE'"

          if [[ -z "$DESC_LINE" || "$DESC_LINE" == "Please describe your changes:" ]]; then
            echo "PR description is missing. Please fill it in."
            exit 1
          fi
